name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  MyJob:
    strategy:
      matrix:
        t1: [1, 2, 3]
        t2: [a, b, c]
    runs-on: ubuntu-latest
    steps:
    - name: perms
      run: echo "${{ matrix.t1 }} x ${{ matrix.t2 }}"


